version: "3.9"

services:
  tinkerpop:
    image: tinkerpop/gremlin-server:latest
    # environment:
    #   POSTGRES_USER: docdrop_user
    #   POSTGRES_PASSWORD: docdrop_password
    ports:
      - '8182:8182'
    # volumes:
    #   - docdrop_postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      # args:
        # args are env vars just for build: https://docs.docker.com/compose/compose-file/compose-file-v3/#args
        # DATABASE_URL: ${DATABASE_URL}
        # INSTALL_PATH: ${INSTALL_PATH}
    # env_file:
    #   - .env
    links:   # Should be unnecessary https://docs.docker.com/compose/networking/#multi-host-networking
      - tinkerpop
    depends_on:
      - tinkerpop
    volumes:
      - .:/trondata
    # working_dir: ${WORKING_DIR}
    command: /bin/bash
# volumes:
#   docdrop_postgres:
