version: "3.9"

services:
  tinkerpop:
    build:
      dockerfile: Dockerfile-tinkergraph
    ports:
      - '8182:8182'
    volumes:
      - .:/ethecycle
  shell:
    build:
      context: .
    env_file:
      - .env
    links:   # Should be unnecessary https://docs.docker.com/compose/networking/#multi-host-networking
      - tinkerpop
    depends_on:
      - tinkerpop
    volumes:
      - .:/ethecycle
      - ${TXION_DATA_DIR}:/trondata
    working_dir: /ethecycle
