version: "3.9"

services:
  neo4j:
    image: neo4j:5.1.0-community
    env_file:
      - .env
    ports:
       - 7474:7474
       - 7687:7687
    volumes:
       - ${NEO4J_DATA_DIR}/data:/data
       - ${NEO4J_DATA_DIR}/logs:/logs
       - .:/ethecycle
  shell:
    build:
      context: .
    env_file:
      - .env
    links:   # Should be unnecessary https://docs.docker.com/compose/networking/#multi-host-networking
      - neo4j
    depends_on:
      - neo4j
    volumes:
      - .:/ethecycle
      - ${TXION_DATA_DIR}:/trondata
    working_dir: /ethecycle
